version: "3.9"

services:
    main:
        container_name: main
        build:
            context: .
        env_file:
            - .production.env
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 5000:5000
        command: npm run start:dev
        depends_on:
            - postgres
        restart: always

    postgres:
        container_name: postgres
        image: postgres
        env_file:
            - .production.env
        environment:
            - PG_DATA=/var/lib/postgres/data
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
        restart: always

volumes:
    db-data:
